/**
 * Flat list of all available persona images for the admin image picker.
 * Each entry has a key, display name, folder (men/women), and require() source.
 */

export interface PersonaImageEntry {
  key: string;
  displayName: string;
  folder: 'men' | 'women';
  source: any;
}

export const ALL_PERSONA_IMAGES: PersonaImageEntry[] = [
  // ===== MEN =====
  { key: 'alex-rivera', displayName: 'Alex Rivera', folder: 'men', source: require('../assets/men/alex-rivera.jpg') },
  { key: 'anders-bergman', displayName: 'Anders Bergman', folder: 'men', source: require('../assets/men/anders-bergman.jpg') },
  { key: 'arjun-mehta', displayName: 'Arjun Mehta', folder: 'men', source: require('../assets/men/arjun-mehta.jpg') },
  { key: 'brett-lawson', displayName: 'Brett Lawson', folder: 'men', source: require('../assets/men/brett-lawson.jpg') },
  { key: 'charles-okafor', displayName: 'Charles Okafor', folder: 'men', source: require('../assets/men/charles-okafor.jpg') },
  { key: 'chris-martinez', displayName: 'Chris Martinez', folder: 'men', source: require('../assets/men/chris-martinez.jpg') },
  { key: 'connor-blake', displayName: 'Connor Blake', folder: 'men', source: require('../assets/men/connor-blake.jpg') },
  { key: 'daniel-hart', displayName: 'Daniel Hart', folder: 'men', source: require('../assets/men/daniel-hart.jpg') },
  { key: 'darnell-washington', displayName: 'Darnell Washington', folder: 'men', source: require('../assets/men/darnell-washington.jpg') },
  { key: 'david-park', displayName: 'David Park', folder: 'men', source: require('../assets/men/david-park.jpg') },
  { key: 'derek-thompson', displayName: 'Derek Thompson', folder: 'men', source: require('../assets/men/derek-thompson.jpg') },
  { key: 'erik-lindgren', displayName: 'Erik Lindgren', folder: 'men', source: require('../assets/men/erik-lindgren.jpg') },
  { key: 'hiroshi-nakamura', displayName: 'Hiroshi Nakamura', folder: 'men', source: require('../assets/men/hiroshi-nakamura.jpg') },
  { key: 'jake-sullivan', displayName: 'Jake Sullivan', folder: 'men', source: require('../assets/men/jake-sullivan.jpg') },
  { key: 'james-morrison', displayName: 'James Morrison', folder: 'men', source: require('../assets/men/james-morrison.jpg') },
  { key: 'jason-wu', displayName: 'Jason Wu', folder: 'men', source: require('../assets/men/jason-wu.jpg') },
  { key: 'jiro-tanaka', displayName: 'Jiro Tanaka', folder: 'men', source: require('../assets/men/jiro-tanaka.jpg') },
  { key: 'jordan-chen', displayName: 'Jordan Chen', folder: 'men', source: require('../assets/men/jordan-chen.jpg') },
  { key: 'kenji-watanabe', displayName: 'Kenji Watanabe', folder: 'men', source: require('../assets/men/kenji-watanabe.jpg') },
  { key: 'kofi-asante', displayName: 'Kofi Asante', folder: 'men', source: require('../assets/men/kofi-asante.jpg') },
  { key: 'logan-pierce', displayName: 'Logan Pierce', folder: 'men', source: require('../assets/men/logan-pierce.jpg') },
  { key: 'lucas-brandt', displayName: 'Lucas Brandt', folder: 'men', source: require('../assets/men/lucas-brandt.jpg') },
  { key: 'marcus-johnson', displayName: 'Marcus Johnson', folder: 'men', source: require('../assets/men/marcus-johnson.jpg') },
  { key: 'marcus-webb-dating', displayName: 'Marcus Webb (Dating)', folder: 'men', source: require('../assets/men/marcus-webb-dating.jpg') },
  { key: 'marcus-webb', displayName: 'Marcus Webb', folder: 'men', source: require('../assets/men/marcus-webb.jpg') },
  { key: 'michael-santos', displayName: 'Michael Santos', folder: 'men', source: require('../assets/men/michael-santos.jpg') },
  { key: 'nils-eriksson', displayName: 'Nils Eriksson', folder: 'men', source: require('../assets/men/nils-eriksson.jpg') },
  { key: 'omar-hassan', displayName: 'Omar Hassan', folder: 'men', source: require('../assets/men/omar-hassan.jpg') },
  { key: 'patrick-doyle', displayName: 'Patrick Doyle', folder: 'men', source: require('../assets/men/patrick-doyle.jpg') },
  { key: 'raj-patel', displayName: 'Raj Patel', folder: 'men', source: require('../assets/men/raj-patel.jpg') },
  { key: 'ryan-callahan', displayName: 'Ryan Callahan', folder: 'men', source: require('../assets/men/ryan-callahan.jpg') },
  { key: 'sam-taylor', displayName: 'Sam Taylor', folder: 'men', source: require('../assets/men/sam-taylor.jpg') },
  { key: 'takeshi-yamada', displayName: 'Takeshi Yamada', folder: 'men', source: require('../assets/men/takeshi-yamada.jpg') },
  { key: 'thomas-obrien', displayName: "Thomas O'Brien", folder: 'men', source: require('../assets/men/thomas-obrien.jpg') },
  { key: 'victor-reyes', displayName: 'Victor Reyes', folder: 'men', source: require('../assets/men/victor-reyes.jpg') },

  // ===== WOMEN =====
  { key: 'aisha-rahman', displayName: 'Aisha Rahman', folder: 'women', source: require('../assets/women/aisha-rahman.jpg') },
  { key: 'alexandra-reed', displayName: 'Alexandra Reed', folder: 'women', source: require('../assets/women/alexandra-reed.jpg') },
  { key: 'amara-diallo', displayName: 'Amara Diallo', folder: 'women', source: require('../assets/women/amara-diallo.jpg') },
  { key: 'andrea-flynn', displayName: 'Andrea Flynn', folder: 'women', source: require('../assets/women/andrea-flynn.jpg') },
  { key: 'astrid-nielsen', displayName: 'Astrid Nielsen', folder: 'women', source: require('../assets/women/astrid-nielsen.jpg') },
  { key: 'bridget-murphy', displayName: 'Bridget Murphy', folder: 'women', source: require('../assets/women/bridget-murphy.jpg') },
  { key: 'carmen-delgado', displayName: 'Carmen Delgado', folder: 'women', source: require('../assets/women/carmen-delgado.jpg') },
  { key: 'catherine-walsh', displayName: 'Catherine Walsh', folder: 'women', source: require('../assets/women/catherine-walsh.jpg') },
  { key: 'claire-dubois', displayName: 'Claire Dubois', folder: 'women', source: require('../assets/women/claire-dubois.jpg') },
  { key: 'diana-novak', displayName: 'Diana Novak', folder: 'women', source: require('../assets/women/diana-novak.jpg') },
  { key: 'elena-petrova', displayName: 'Elena Petrova', folder: 'women', source: require('../assets/women/elena-petrova.jpg') },
  { key: 'elena-volkov', displayName: 'Elena Volkov', folder: 'women', source: require('../assets/women/elena-volkov.jpg') },
  { key: 'emma-larsson', displayName: 'Emma Larsson', folder: 'women', source: require('../assets/women/emma-larsson.jpg') },
  { key: 'eva-lindqvist', displayName: 'Eva Lindqvist', folder: 'women', source: require('../assets/women/eva-lindqvist.jpg') },
  { key: 'fiona-gallagher', displayName: 'Fiona Gallagher', folder: 'women', source: require('../assets/women/fiona-gallagher.jpg') },
  { key: 'grace-williams', displayName: 'Grace Williams', folder: 'women', source: require('../assets/women/grace-williams.jpg') },
  { key: 'hannah-brooks', displayName: 'Hannah Brooks', folder: 'women', source: require('../assets/women/hannah-brooks.jpg') },
  { key: 'helen-crawford', displayName: 'Helen Crawford', folder: 'women', source: require('../assets/women/helen-crawford.jpg') },
  { key: 'ingrid-svensson', displayName: 'Ingrid Svensson', folder: 'women', source: require('../assets/women/ingrid-svensson.jpg') },
  { key: 'jessica-taylor', displayName: 'Jessica Taylor', folder: 'women', source: require('../assets/women/jessica-taylor.jpg') },
  { key: 'julia-kovacs', displayName: 'Julia Kovacs', folder: 'women', source: require('../assets/women/julia-kovacs.jpg') },
  { key: 'karen-whitfield', displayName: 'Karen Whitfield', folder: 'women', source: require('../assets/women/karen-whitfield.jpg') },
  { key: 'kelly-anderson', displayName: 'Kelly Anderson', folder: 'women', source: require('../assets/women/kelly-anderson.jpg') },
  { key: 'elsa-bergstrom', displayName: 'Elsa Bergstrom', folder: 'women', source: require('../assets/women/elsa-bergstrom.jpg') },
  { key: 'lisa-moretti', displayName: 'Lisa Moretti', folder: 'women', source: require('../assets/women/lisa-moretti.jpg') },
  { key: 'margaret-brennan', displayName: 'Margaret Brennan', folder: 'women', source: require('../assets/women/margaret-brennan.jpg') },
  { key: 'maya-chen', displayName: 'Maya Chen', folder: 'women', source: require('../assets/women/maya-chen.jpg') },
  { key: 'maya-jensen', displayName: 'Maya Jensen', folder: 'women', source: require('../assets/women/maya-jensen.jpg') },
  { key: 'mia-chang', displayName: 'Mia Chang', folder: 'women', source: require('../assets/women/mia-chang.jpg') },
  { key: 'nadia-karim', displayName: 'Nadia Karim', folder: 'women', source: require('../assets/women/nadia-karim.jpg') },
  { key: 'natalie-winter', displayName: 'Natalie Winter', folder: 'women', source: require('../assets/women/natalie-winter.jpg') },
  { key: 'natasha-volkov', displayName: 'Natasha Volkov', folder: 'women', source: require('../assets/women/natasha-volkov.jpg') },
  { key: 'nina-larsson', displayName: 'Nina Larsson', folder: 'women', source: require('../assets/women/nina-larsson.jpg') },
  { key: 'patricia-keane', displayName: 'Patricia Keane', folder: 'women', source: require('../assets/women/patricia-keane.jpg') },
  { key: 'erin-calloway', displayName: 'Erin Calloway', folder: 'women', source: require('../assets/women/erin-calloway.jpg') },
  { key: 'rachel-stevens', displayName: 'Rachel Stevens', folder: 'women', source: require('../assets/women/rachel-stevens.jpg') },
  { key: 'sarah-bennett', displayName: 'Sarah Bennett', folder: 'women', source: require('../assets/women/sarah-bennett.jpg') },
  { key: 'sarah-mitchell', displayName: 'Sarah Mitchell', folder: 'women', source: require('../assets/women/sarah-mitchell.jpg') },
  { key: 'sienna-donovan', displayName: 'Sienna Donovan', folder: 'women', source: require('../assets/women/sienna-donovan.jpg') },
  { key: 'sophia-adeyemi', displayName: 'Sophia Adeyemi', folder: 'women', source: require('../assets/women/sophia-adeyemi.jpg') },
  { key: 'tessa-grant', displayName: 'Tessa Grant', folder: 'women', source: require('../assets/women/tessa-grant.jpg') },
  { key: 'adaeze-obi', displayName: 'Adaeze Obi', folder: 'women', source: require('../assets/women/adaeze-obi.jpg') },
  { key: 'victoria-blackwell', displayName: 'Victoria Blackwell', folder: 'women', source: require('../assets/women/victoria-blackwell.jpg') },
  { key: 'yuki-tanaka', displayName: 'Yuki Tanaka', folder: 'women', source: require('../assets/women/yuki-tanaka.jpg') },
  { key: 'karin-lindberg', displayName: 'Karin Lindberg', folder: 'women', source: require('../assets/women/karin-lindberg.jpg') },
  { key: 'zara-khoury', displayName: 'Zara Khoury', folder: 'women', source: require('../assets/women/zara-khoury.jpg') },
];
